import { useState } from "react";
import Head from "next/head";
import { Navbar } from "@/components/navigation";
import { AboutMe, ExperienceSection, Profile } from "@/components/sections";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const onToggleTheme = () => setDarkMode(!darkMode);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Anthony McGarry Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <Navbar toggleTheme={onToggleTheme} />
        <Profile />
        <AboutMe />
        <ExperienceSection />
      </main>
    </div>
  );
}
